name: Media Ops

on:
  workflow_dispatch:

jobs:
  call-compile-workflow:
    name: Call Media Ops
    uses: IDEMSInternational/parenttext-core/.github/workflows/media_ops.yaml@media_workflows
    secrets:
      GCP_CREDENTIALS: ${{ secrets.GCP_CREDENTIALS }}
      CANTO_APP_ID: ${{ secrets.CANTO_APP_ID }}
      CANTO_APP_SECRET: ${{ secrets.CANTO_APP_SECRET }}
      CANTO_USER_ID: ${{ secrets.CANTO_USER_ID }}
      DEPLOYMENT_ASSET_LOCATION: ${{ secrets.DEPLOYMENT_ASSET_LOCATION }}
      GCS_PROJECT_ID: ${{ secrets.GCS_PROJECT_ID }}
      GCS_BUCKET_NAME: ${{ secrets.GCS_BUCKET_NAME }}
